### ISSUE TITLE
Icon Frame emptying

### ISSUE THREAD

**Issue by schanze** [Geigerkind/ModifiedPowerAurasTBC#1]
As you change categories in the Icon Frame more and more slots become empty.
![404](https://cloud.githubusercontent.com/assets/7439234/23582520/6e880e6c-012c-11e7-8fcb-b6fb1cba7dee.png)
![405](https://cloud.githubusercontent.com/assets/7439234/23582523/72e3101a-012c-11e7-829e-0986a95a8173.png)

Also if you're taking suggestions I would change the show hundredths into show tenths. I'll call everyone who says he can process hundreths of seconds in a timer live a liar.

**Comment by tdymel** [comment]
Fixed!
