### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by schanze** [Geigerkind/ModifiedPowerAurasTBC#10]
Since release b48 whenever I use an aura with a timer it will give me:
zzzModifiedPowerAuras\Auras.lua:162: attempt to index global 'path' (a nil value)
zzzModifiedPowerAuras\Auras.lua:121: in function `OnUpdate'
zzzModifiedPowerAuras\Start.lua:242: in function <Interface\AddOns\zzzModifiedPowerAuras\Start.lua:242>

The icon will show up without a timer and continue to spout errors for the whole duration.

As a side note: After I suggested to change the hundredths to tenths you changed the text in the menu but the option still enables hundredths to be shown.

**Comment by tdymel** [comment]
Fixed, thy!
