### ISSUE TITLE
Dynamic grouping issues + suggestions

### ISSUE THREAD

**Issue by Redtuzk** [Geigerkind/ModifiedPowerAurasTBC#11]
Dynamic groups don't seem to group the icons properly together most of the time, misplaces or overlaps them.
Not sure how to be more descriptive I'm afraid, the function sadly doesn't seem to work properly atm.

These aren't bugs, but I thought i'd include it anyway; 

1. It'd be nice to be able to adjust the stack font size, since it's nearly unreadable depending on icon size.
2. The "cooldown clock" effect would be a nice addition for at-a-glance viewing if a buff is about to expire.

Appreciate this mod a lot though, heaps better than stock PA or TMW 👍

**Comment by tdymel** [comment]
Cooldown clock? 
You mean that at 1 sec some sort of gray circle collapses degree by degree?

**Comment by Redtuzk** [comment]
@Geigerkind Yea, exactly. An option for enabling that would be awesome.

**Comment by tdymel** [comment]
For the group feature to not overlap, the icons need to have the same size

**Comment by Redtuzk** [comment]
@Geigerkind I'll test it again real quick, but I'm 99% sure that my icons had exactly the same settings. Will report back in a couple of minutes.

**Comment by Redtuzk** [comment]
@Geigerkind Alright, tested it again.

Icon 1's settings: http://i.imgur.com/MjPHoog.png
Icon 2's settings: http://i.imgur.com/CVsbWDC.png
Positioning **before** grouping: http://i.imgur.com/5m6Ivyo.png
Positioning **after** grouping (that was the only change I made): http://i.imgur.com/KxnJXbi.png

**Comment by tdymel** [comment]
Parentgroup(1): http://i.imgur.com/BqgaQVY.png
Childnode(2): http://i.imgur.com/vx661Ke.png

That is how it needs to be configured

**Comment by Redtuzk** [comment]
@Geigerkind Ah, that makes more sense then. I understood it as you label icons together in group numbers, such that 2 icons must have the same number. 

Edit: Nope, still broken after reloading, icons mispositioned and forgets group label.

**Comment by tdymel** [comment]
Added your feature requests btw

Enjoy :)

**Comment by Redtuzk** [comment]
@Geigerkind Thanks man! :D
