### ISSUE TITLE
Addons conflict.

### ISSUE THREAD

**Issue by vasecha** [Geigerkind/ModifiedPowerAurasTBC#12]
Hello. 
Im getting this error 
http://i.imgur.com/tXRxbCW.jpg
runing mpowa-tbc among witn addon named BankItems
https://www.wowace.com/projects/bank-items/files?filter-game-version=2020709689%3A41
Is there anything can be done on your side?
Thank you in advance.

**Comment by tdymel** [comment]
Update to the newest version

**Comment by vasecha** [comment]
Thank you for the quick update! Now there is no conflict with the addon mentioned above. However, option "invert" doesnt work in latest release.
Syncerely.
