### ISSUE TITLE
Auras gone after relog

### ISSUE THREAD

**Issue by markopavlovic** [Geigerkind/ModifiedPowerAurasTBC#16]
I can't seem to be able to save auras, every time I relog they are gone, I save profiles, but importing them doesn't work also. Any ideas?

**Comment by Niylah** [comment]
Same problem here. Im using build 54.

**Comment by tdymel** [comment]
Yep, its apparently a problem caused by the latest release, use b53 for now until b55 comes out. Also save your MPOWA.lua in your char saved vars.

cheers!

**Comment by tdymel** [comment]
Fixed, Im sorry!
