### ISSUE TITLE
Sounds don't work

### ISSUE THREAD

**Issue by jonomurphy** [Geigerkind/ModifiedPowerAurasTBC#17]
Using mpowa picking sounds yet they don't seem to work. I will select sound to play when aura fades out/in, but none of them work. Awesome add-on otherwise!

**Comment by tdymel** [comment]
Alright, will take a look at it later!

**Comment by jonomurphy** [comment]
Awesome! Really love the addon, and I'm sure its not an addon conflicting with Mpowa, so I'm at a loss as to what it could be. Thanks man.

**Comment by tdymel** [comment]
Works for me, maybe you picket a sound that doesnt work or you have sounds disabled?

Maybe send me your configuration.

**Comment by jonomurphy** [comment]
I have all sounds/ambience on, except error sounds and music. Sound quality high. 

I go to /mpowa, pick my CD (Mind blast, for example), and tick 'Play sound when aura fades'. I choose a sound (all of the sounds work when I cycle through them to test), and test the cooldown in combat - but the sound doesn't work.

**Comment by jonomurphy** [comment]
Made a quick vid
https://www.youtube.com/watch?v=zCWkDxyUw_Q&feature=youtu.be

**Comment by tdymel** [comment]
a cooldown, i see

**Comment by tdymel** [comment]
Fixed
