### ISSUE TITLE
[I must be getting on your nerves now] - Sounds

### ISSUE THREAD

**Issue by jonomurphy** [Geigerkind/ModifiedPowerAurasTBC#18]
I just thought i'd let you know that I tested the sounds, and only the DEFAULT wow sounds (readycheck,questcompleted, etc.) are working. None of the custom sounds are.

**Comment by tdymel** [comment]
Hmm, I tested it yesterday with some non default sounds ^^

**Comment by jonomurphy** [comment]
I will go through it later and try to find out what sounds are or aren't working. Just know that when I tried it, none of the custom sounds worked.

**Comment by jonomurphy** [comment]
Tested it again, only default sounds are working. Non-custom sounds do not go off, despite working in the /mpowa - sound box.

**Comment by tdymel** [comment]
Nvm me fixed
