### ISSUE TITLE
hulk

### ISSUE THREAD

**Issue by schanze** [Geigerkind/ModifiedPowerAurasTBC#2]
![200pulshabich](https://cloud.githubusercontent.com/assets/7439234/23878826/f113e01c-0849-11e7-9a10-e3c26dbbbc5e.png)

**Comment by tdymel** [comment]
So beautiful :O

Edit: Did you rename the folder to "末ModifiedPowerAuras" ?

**Comment by schanze** [comment]
No I renamed the .toc because the addon didnt load at first and it had a square thing in it...

**Comment by tdymel** [comment]
I see, aight

**Comment by schanze** [comment]
But yeah i just tried and it works if I copy the square for missing characters in the folder name instead.

**Comment by tdymel** [comment]
Fixed, download the new addon and rename the folder to zzzModifiedPowerAuras
