### ISSUE TITLE
Tracking friendly/group buffs (such as Heroism)

### ISSUE THREAD

**Issue by jonomurphy** [Geigerkind/ModifiedPowerAurasTBC#21]
(Foreword: these are more queries, but I do not know how to contact you so I am writing it here. I apologise in advance, and if there is a place I can contact you if I have queries about using your addon, please let me know. As usual - much love!)

Is it possible to track Heroism and other such group-wide buffs with Mpowa? I write in the name of the effect, click 'on myself', yet it doesn't seem to work when a Shaman activates it.

Appreciate your help.

**Comment by tdymel** [comment]
Should be ya, dunno if its bugged in TBC

**Comment by tdymel** [comment]
Works like a charm
