### ISSUE TITLE
cooldown timer w/ tenths of seconds

### ISSUE THREAD

**Issue by schanze** [Geigerkind/ModifiedPowerAurasTBC#23]
If you start a regular cooldown timer it will show 1 at 1 seconds left then wait another second and the icon will disappear.
If you start a cooldown timer with thenths of seconds enabled it will start 1 second ahead and reach 1 second when the cooldown is gone instead of showing 0.x seconds for the last second.

**Comment by tdymel** [comment]
Fixed
