### ISSUE TITLE
Client crash, possible addon conflict?

### ISSUE THREAD

**Issue by Ofecks** [Geigerkind/ModifiedPowerAurasTBC#25]
I set up an aura for a short-duration buff (Slice and Dice, to be exact) and if I enable the timer flash with 5 seconds remaining, sometimes when it reads 3, the game will freeze.  Afterwards, if I alt-tab and re-click the game window, it will close on its own, I don't get the blizzard crash box.  I disabled all other addons, then testing yours with each one enabled, one by one, yet it was working ok once they were all enabled, so that was inconclusive.  I then went back to Shattrath, vendored some stuff, mailed an item (I have both the VendorValues and Postal addons), then I flew to Telaar in Nagrand, made some poisons, and headed out to kill/skin some beasts.  Killed a Cleftoof Bull, no issue.  Killed 2 talbuks w/ Slice and Dice + Blade Flurry active (I also made an aura for BF using the timer flash setting), and it crashed when the SnD timer reached 3.  At first I thought it was a combination of the timer flash + and ending animation, but I turned off the ending animation for SnD, attempted to kill another Clefthoof, and it happened again.  Going back to NeedToKnow/TellMeWhen until you can figure it out and fix.  Thanks.

**Comment by tdymel** [comment]
Hmm

**Comment by tdymel** [comment]
Fixed a potential issue causing this issue.
