### ISSUE TITLE
Mpowa

### ISSUE THREAD

**Issue by shexnaex123** [Geigerkind/ModifiedPowerAurasTBC#27]
Any chance to add bars so we can track buffs/debuffs similar to class timer?

**Comment by Arcitec** [comment]
https://github.com/ElvUI-TBC/ElvUI

This GUI by default shows buff and debuff timers on yourself and your target.

PS: Mpowa is a very buggy and sadly dead addon (look at the age of the unanswered issues on this tracker), unfortunately. You can just track most things via the default buff-bars in ElvUI instead. But I like the graphical style of MPOWA for some vital buffs...

**Comment by shexnaex123** [comment]
Weak Auras for TBC would be sick. But damn no one backported it

**Comment by tdymel** [comment]
Nah, I wont add bars. Thats not what the Power auras, that I love was designed for. I hear a Weak Auras backport is in work tho from a guild called "Hymn".
