### ISSUE TITLE
"Mine" modifier is totally broken

### ISSUE THREAD

**Issue by Arcitec** [Geigerkind/ModifiedPowerAurasTBC#28]
Below the buff name there's a "Mine" checkbox saying "indicates if the buff was cast by you". If this option is enabled, it fails to find the buff reliably. Tested with Commanding Shout as a warrior.

**Comment by tdymel** [comment]
I think it is an extension of the BuffLib, meaning it does not work for cases described in the lib. Adding a tooltip that warns for such things may be helpful, ya

**Comment by Arcitec** [comment]
Oh, okay so it's a limit of the library... Hmm. And this seems tough to solve.

```
[04:01] Dump: value=UnitAura("player", 3) 
[04:01] [1]="Battle Shout", 
[04:01] [2]="Rank 8", 
[04:01] [3]="Interface\\Icons\\Ability_Warrior_BattleShout", 
[04:01] [4]=1, 
[04:01] [6]=120, 
[04:01] [7]=112.568
```

As you see... there's no info about caster in the UnitAura details in TBC. In later WoW versions, there's a caster as `[8]`. But not here...

Well... just adding a tooltip that warns that "Mine" doesn't work for all buffs, is enough...

**Comment by tdymel** [comment]
Added comment.
