### ISSUE TITLE
Found reason behind broken modifier buttons!

### ISSUE THREAD

**Issue by Arcitec** [Geigerkind/ModifiedPowerAurasTBC#30]
By default, values such as "in raid instance" default like this:

```
["inraidinstance"] = 0, -- or 1 for "on"
```

If you edit the setting, they get changed to this:

```
["inraidinstance"] = false, -- or true for "on"
```

This is the reason why the GUI settings bug out and "don't get saved". They need to be saved as 1/0 (and probably others for the "not" inverted mode such as "not mounted"), not true/false. Otherwise they break on the next UI reload.

**Comment by Arcitec** [comment]
Ping @Geigerkind Tom.

**Comment by tdymel** [comment]
ok, will take a look at it

**Comment by Arcitec** [comment]
@Geigerkind Wonderful. Thank you! If we're lucky, this fixes many of the bugs in the addon.

I also discovered why IsMounted isn't working: https://github.com/Geigerkind/ModifiedPowerAurasTBC/issues/22

**Comment by tdymel** [comment]
The issue was somewhere else, but its fixed now

**Comment by Arcitec** [comment]
@Geigerkind Beautiful, thank you so much! I still love this addon, because I've checked its CPU impact and was SHOCKED that it uses almost 0% CPU, despite all the cool auras it can produce and track. So it's going to be fun to test the addon update now, and see if its advanced aura features work now! :-D

**Comment by tdymel** [comment]
Im surprised about that, thanks :>

**Comment by Arcitec** [comment]
@Geigerkind I know you use ElvUI, so you can actually verify it! Type `/console scriptProfile 1` and restart WoW. Then you will be able to hover the System datatext (default: bottom right panel, says FPS and Ping). It will then show a list of all addons and how many milliseconds the CPU has spent on them.

It's always like "ElvUI: 500000 ms, QuestHelper (worst coded addon I've seen in a long time (it always re-does identical work like 20 times in a row per frame OnUpdate, rather than caching it); I did a [backport for TBC](https://github.com/VideoPlayerCode/QuestHelperTBC)): 900000 ms, MPOWA: 132 ms"! :-)
