### ISSUE TITLE
forbidden function CastSpellByName

### ISSUE THREAD

**Issue by Flaktrack** [Geigerkind/ModifiedPowerAurasTBC#6]
Greetings!

Thanks for this great addon, as it enhances the standard PowerAuras noticeable.
but ;-)
I got an error after executing the following macro:

**/castsequence reset=combat/60  Strength of Earth Totem, Grace of Air Totem, Mana Spring Totem, Searing Totem**
(placing all four totems in a sequence)

***************************************************************************************

["message"] = **"Error: AddOn zzzModifiedPowerAuras attempted to call a forbidden function (CastSpellByName()) from a tainted execution path."**,
			["count"] = 28,
			["addons"] = "  AckisRecipeList, v0.9372\n  AllPlayed, v20400-2 110\n  Aloft, vr416\n  Altoholic, v2.4.016\n  Atlas, v1.12.0\n  AtlasBattlegrounds, v1.12.0\n  AtlasDungeonLocs, v1.12.0\n  AtlasFlightPaths, v1.12.0\n  AtlasOutdoorRaids, v1.12.0\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v4.06.04|r\n  AucAdvanced, v5.0.0\n  AucFilterBasic, v5.0.0 (BillyGoat)\n  AucStatClassic, v5.0.0 (BillyGoat)\n  AucStatHistogram, v5.0.0 (BillyGoat)\n  AucStatPurchased, v5.0.0 (BillyGoat)\n  AucStatSimple, v5.0.0 (BillyGoat)\n  AucStatStdDev, v5.0.0 (BillyGoat)\n  Auctionator\n  Auctioneer, v5.0.0\n  Bartender4, v4.0\n  BeanCounter, v5.0.0 (BillyGoat)\n  Cartographer, vr2250\n  CartographerBattlegrounds, v2.0\n  CartographerCoordinates, v2.0\n  CartographerGroupColors, v2.0\n  CartographerGuildPositions, v2.0\n  CartographerInstanceLoot, v2.0\n  CartographerInstanceMaps, v2.0\n  CartographerInstanceNotes, v2.0\n  CartographerLookNFeel, v2.0\n  CartographerNotes, v2.0\n  CartographerPOI, v2.0\n  CartographerProfessions, v2.0\n  CartographerWaypoints, v2.0\n  CartographerZoneInfo, v2.0\n  CensusPlus, v4.1.8\n  Chinchilla, v1.0r80034\n  ClearFont2, v2.4\n  CombatLogReset, v1.1\n  Critline, vv5.2.4\n  DrDamage, v1.5.0\n  ElkBuffBars, v2.1\n  Enchantrix, v5.0.0\n  EnchantrixBarker, v5.0.0 (BillyGoat)\n  EnhTooltip, v5.0.0\n  EveryQuest, v13\n  FishingBuddy, v0.9.4l\n  FuBarAtlasFu\n  FuBarClockFu, v3.0\n  FuBarCritlineDmg, v1.2.4\n  FubarCritlineHeal, v1.2.4\n  FuBarDurabilityFu, v2.0\n  FuBarEmoteFu2, v0.1.5\n  FuBarExperienceFu, v1.1 $Revision: 65606 $\n  FuBarFactionsFu, v2.2\n  FuBarFriendsFu, v2.4\n  FuBarGuildFu, v2.4\n  FuBarImpulseStatsFu, v0.3b\n  FuBarLocationFu, v3.0\n  FuBarMoneyFu, vv1.1\n  FuBarPerformanceFu, v2.0\n  FuBarRecountFu, v3.4\n  FuBarRoutesFu\n  FuBarSpeedFu, v2.0.$Revision: 55081 $\n  FuBar, v90003\n  Gatherer, v3.1.2\n  GatherMate, v1.0\n  HealBot, v2.4.3.16\n  Informant, v5.0.0\n  ImpulseBooster, v3.1\n  LightHeaded, v274\n  MikScrollingBattleText, v5.2.14\n  MobInfo2, v3.61\n  zzzModifiedPowerAuras\n  oGlow, v1.12\n  Omen, vOmen r79486 / Threat-2.0 r90000\n  OmniCC, v2.1.1\n  Postal, v2.1 |cffff8888r79759|r\n  Prat, v2.0 79344\n  Quartz, v0.1.0\n  QuestGuru, v0.9.3\n  QuestHelper, v0.54\n  Recount, v79128\n  Routes, v1.0\n  ShadowedUnitFrames, vBackport v.01 from v3.2.12-5-g3fb7edd\n  SharedMedia, v3.0\n  SharedMediaAdditionalFonts, v1.0\n  SilverDragon, v2.0.65654\n  Stubby, v93\n  Swatter, v5.0.0\n  Talented, v1.3\n  TotemTimers, v8.1d\n  TradeskillInfo, v1.0.144\n  xDamageFont, v20400\n  XLoot, v0.9\n  DBMAPI\n",
			["timestamp"] = "2017-06-03 16:59:10",
			["context"] = "AddOn: zzzModifiedPowerAuras",
			["stack"] = "[C]: in function `CastSpellByName'\nInterface\\FrameXML\\ChatFrame.lua:692: in function <Interface\\FrameXML\\ChatFrame.lua:624>\nInterface\\FrameXML\\ChatFrame.lua:842: in function `?'\nInterface\\FrameXML\\ChatFrame.lua:3032: in function <Interface\\FrameXML\\ChatFrame.lua:3003>\n[C]: in function `ChatEdit_ParseText'\nInterface\\FrameXML\\ChatFrame.lua:2770: in function `ChatEdit_SendText'\nInterface\\FrameXML\\ChatFrame.lua:1921: in function <Interface\\FrameXML\\ChatFrame.lua:1914>\n[C]: in function `UseAction'\nInterface\\FrameXML\\SecureTemplates.lua:266: in function `SecureActionButton_OnClick'\n[string \"*:OnClick\"]:1: in function <[string \"*:OnClick\"]:1>\n(tail call): ?\n[C]: in function `securecall'\nInterface\\FrameXML\\SecureStateHeader.lua:1052: in function <Interface\\FrameXML\\SecureStateHeader.lua:1033>\n",
		}, -- [50]

*************************************************************************************************
_When i disabled zzzModifiedPowerAuras the macro worked fine._

**Comment by tdymel** [comment]
Can you tell me if you have some of these auras that you use there as aura in power auras?

**Comment by tdymel** [comment]
Okay, fixed it!
Was a little more tricky than I thought.
