### ISSUE TITLE
Debuff tick box

### ISSUE THREAD

**Issue by schanze** [Geigerkind/ModifiedPowerAurasTBC#7]
When I tick "debuff" I get:
<string>:"MPowa_ConfigFrame_Container_1_2_Checkbutton_Debuff:OnClick":3: attempt to index global 'MPowa_ConfigFrame_Container_1_2_Editbox_DebuffDuration' (a nil value)

But the feature itself works.
This was already present in the last release b47.

**Comment by tdymel** [comment]
Thy!
