### ISSUE TITLE
Ratingbuster

### ISSUE THREAD

**Issue by schanze** [Geigerkind/ModifiedPowerAurasTBC#8]
When I use ModifiedPowerAuras with RatingBuster I get:

TipHooker-1.0-90052:241: attempt to call method 'GetObjectType' (a nil value)
AceAddon-2.0-91091 (Grid):983: in function <...rface\AddOns\Grid\libs\AceAddon-2.0\AceAddon-2.0.lua:976>
<in C code>: ?
AceEvent-2.0-91091 (Grid):260: in function `TriggerEvent'
AceEvent-2.0-91091 (Grid):910: in function <...rface\AddOns\Grid\libs\AceEvent-2.0\AceEvent-2.0.lua:903>

RatingBuster won't work at all ModifiedPowerAuras works fine.
This was already present in the last release b47.

**Comment by tdymel** [comment]
Fixed with CowTip issue
